[package]
name = "zaco-runtime-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "fs", "sync"] }
libc = "0.2"
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = "1.0"
